title: "spaceTree Documentation"
remote_theme: pmarsceill/just-the-docs

# Optional settings for the theme
search_enabled: true
search_tokenizer_separator: /[\s/]+/
search_preview_length: 15
search_result_path: /search/

# Site settings
logo: "space_tree.png"  # Ensure this path is correct
description: >- 
  Welcome to the official documentation for spaceTree! Here, you will find tutorials and guides to help you get started and make the most out of our tool.
baseurl: "/spaceTree"  # The subpath of your site (relative to the domain root)
url: "https://pmbio.github.io" # The base hostname & protocol for your site

# Navigation settings for Just the Docs
just_the_docs:
  logo: "space_tree.png"
  logo_alt: "spacetree logo"
  aux_links:
    "View on GitHub":
      url: "https://github.com/PMBio/spaceTree"
      icon: "fab fa-github"  # Optional: Adds a GitHub icon

# Sidebar navigation configuration
nav:
  - title: "Home"
    url: "/spaceTree/"
  - title: "Installation"
    url: "/spaceTree/installation"
  - title: "Tutorials"
    children:
      - title: "Visium/grid-based data"
        url: "/spaceTree/tutorials/cell-state-clone-mapping"
      - title: "Xenium data"
        url: "/spaceTree/tutorials/cell-state-clone-mapping-xenium"
