title: "spaceTree Documentation"
remote_theme: pmarsceill/just-the-docs

# Optional settings for the theme
search_enabled: false
search_tokenizer_separator: /[\s/]+/
search_preview_length: 15
search_result_path: /search/

# Site settings
logo: "space_tree.png"  # Ensure this path is correct
description: >- 
  Welcome to the official documentation for spaceTree! Here, you will find tutorials and guides to help you get started and make the most out of our tool.
baseurl: "/spaceTree"  # The subpath of your site (relative to the domain root)
url: "https://pmbio.github.io" # The base hostname & protocol for your site

# Auxiliary links configuration
aux_links:
  "View on GitHub":
    - "https://github.com/PMBio/spaceTree"
# Show edit links on GitHub
show_edit_on_github: true
aux_links_new_tab: true

# Navigation settings for Just the Docs
just_the_docs:
  logo: "space_tree.png"
  logo_alt: "spacetree logo"

# Sidebar navigation configuration
nav:
  - title: "Home"
    url: "/spaceTree/"
  - title: "Installation"
    url: "/spaceTree/installation"
  - title: "Tutorials"
    children:
      - title: "Visium/grid-based data"
        url: "/spaceTree/tutorials/cell-state-clone-mapping"
      - title: "Xenium data"
        url: "/spaceTree/tutorials/cell-state-clone-mapping-xenium"
      - title: "Visium HD tips and tricks"
        url: "/spaceTree/tutorials/visium-hd"
nav_external_links:
  - title: View on GitHub
    url: https://github.com/PMBio/spaceTree


back_to_top: true
back_to_top_text: "Back to top"

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/PMBio/spaceTree" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately