title: "spaceTree Documentation"
remote_theme: "just-the-docs/just-the-docs"

# Site settings
description: >-
  Welcome to the official documentation for spaceTree! Here, you will find tutorials and guides to help you get started and make the most out of our tool.
baseurl: "/spaceTree"  # The subpath of your site (relative to the domain root)
url: "https://pmbio.github.io"  # The base hostname & protocol for your site

# Just the Docs theme settings
just_the_docs:
  # Logo configuration
  logo:
    src: "space_tree.png"  # Adjust the path to your logo
    alt: "spaceTree logo"

  # Search settings
  search:
    enabled: true
    tokenizer_separator: /[\s/]+/
    preview_length: 15

  # Repository settings for "Edit on GitHub" links
  repository:
    base_url: "https://github.com/PMBio/spaceTree"  # The GitHub URL for your repo
    branch: "master"  # The branch that your docs are served from
    subdirectory: "docs"

  # Enabling "Edit this page" links
  editing:
    enabled: true
    edit_on_github_text: "Edit this page on GitHub"

# Optional: Enable breadcrumbs (if desired)
breadcrumbs:
  enabled: true
