name: Publish Python Package

on:
  release:
    types:
      - created  # This workflow will run when a new release is created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Ensure the Python version matches your project

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    # - name: Publish to PyPI
    #   env:
    #     TWINE_USERNAME: "__token__"
    #     TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
    #   run: |
    #     python -m pip install --upgrade twine
    #     twine upload dist/*
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.10
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
